name: five_widgets_architecture
description: A Flutter architecture to write pragmatic maintainable apps.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  fast_immutable_collections: ^7.4.2

  flutter:
    sdk: flutter

  flutter_riverpod: ^1.0.3+1
  freezed_annotation: ^2.1.0
  riverbloc: ^1.0.0+2
  shared_preferences: ^2.0.15
  uuid: ^3.0.6
  widgetbook_annotation: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  widgetbook: ^2.4.1
  widgetbook_generator: ^2.4.1
  build_runner: ^2.2.1
  json_serializable: ^6.3.2
  freezed: ^2.1.0+1

flutter:
  uses-material-design: true
